version: '3.8'

services:
  shorturl-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=shorturl-db;Database=urlsdata;User=root;Password=root;
    depends_on:
      - shorturl-db
    networks:
      - shorturl-network

  shorturl-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=urlsdata
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shorturl-network

volumes:
   mysql_data:

networks:
  shorturl-network:
    driver: bridge