// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestShortUrl.Data;

#nullable disable

namespace TestShortUrl.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestShortUrl.Entities.ShortUrl", b =>
                {
                    b.Property<string>("NewUrl")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("OldUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NewUrl");

                    b.ToTable("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
